baseurl = "https://dist.ipfs.tech"
relativeurls = true
languageCode = "en-us"
title = "IPFS Distributions"

# No tags/categories
taxonomies = {}

[params]
hiddenDists = ['go-ipfs', 'gx', 'gx-go', 'libp2p-relay-daemon', 'ipfs-ds-convert']
newGoIpfsName = 'kubo'

[params.targetMap]
386 = "32-bit"
amd64 = "64-bit"
arm = "ARM"
arm64 = "ARM-64"

[params.architectureMap]
darwin = "macOS Binary"
freebsd = "FreeBSD Binary"
openbsd = "OpenBSD Binary"
linux = "Linux Binary"
windows = "Windows Binary"
